from utility import bytes_to_int
from .utils import _read_attribute, _read_telemetry
from config import BYTE_ORDER


def extract(byte_data):
    # client attributes
    atsVacP1State = bytes_to_int(byte_data[0])
    atsVacP2State = bytes_to_int(byte_data[1])
    atsVacP3State = bytes_to_int(byte_data[2])
    atsVgenP1State = bytes_to_int(byte_data[3])
    atsVgenP2State = bytes_to_int(byte_data[4])
    atsVgenP3State = bytes_to_int(byte_data[5])
    atsContactorElecState = bytes_to_int(byte_data[6])
    atsContactorGenState = bytes_to_int(byte_data[7])
    atsAcState = bytes_to_int(byte_data[8])
    atsGenState = bytes_to_int(byte_data[9])
    atsState = bytes_to_int(byte_data[10])
    atsErrorState = bytes_to_int(byte_data[11])
    atsMode = bytes_to_int(byte_data[12])
    atsConnect = bytes_to_int(byte_data[49])
    atsVgenThresholdState = bytes_to_int(byte_data[50])
    atsVacThresholdState = bytes_to_int(byte_data[51])

    #telemetry
    atsVacFreq = bytes_to_int(byte_data[13:15], byteorder=BYTE_ORDER)
    atsVgenFreq = bytes_to_int(byte_data[15:17], byteorder=BYTE_ORDER)
    atsVloadFreq = bytes_to_int(byte_data[17:19], byteorder=BYTE_ORDER)
    atsVacP1 = bytes_to_int(byte_data[19:21], byteorder=BYTE_ORDER)
    atsVacP2 = bytes_to_int(byte_data[21:23], byteorder=BYTE_ORDER)
    atsVacP3 = bytes_to_int(byte_data[23:25], byteorder=BYTE_ORDER)
    atsVgenP1 = bytes_to_int(byte_data[25:27], byteorder=BYTE_ORDER)
    atsVgenP2 = bytes_to_int(byte_data[27:29], byteorder=BYTE_ORDER)
    atsVgenP3 = bytes_to_int(byte_data[29:31], byteorder=BYTE_ORDER)
    atsVloadP1 = bytes_to_int(byte_data[31:33], byteorder=BYTE_ORDER)
    atsVloadP2 = bytes_to_int(byte_data[33:35], byteorder=BYTE_ORDER)
    atsVloadP3 = bytes_to_int(byte_data[35:37], byteorder=BYTE_ORDER)
    atsIloadP1 = bytes_to_int(byte_data[37:39], byteorder=BYTE_ORDER)
    atsIloadP2 = bytes_to_int(byte_data[39:41], byteorder=BYTE_ORDER)
    atsIloadP3 = bytes_to_int(byte_data[41:43], byteorder=BYTE_ORDER)
    atsPac1 = bytes_to_int(byte_data[43:45], byteorder=BYTE_ORDER)
    atsPac2 = bytes_to_int(byte_data[45:47], byteorder=BYTE_ORDER)
    atsPac3 = bytes_to_int(byte_data[47:49], byteorder=BYTE_ORDER)

    # telemetry
    _read_telemetry('atsVacFreq', atsVacFreq)
    _read_telemetry('atsVgenFreq', atsVgenFreq)
    _read_telemetry('atsVloadFreq', atsVloadFreq)
    _read_telemetry('atsVacP1', atsVacP1)
    _read_telemetry('atsVacP2', atsVacP2)
    _read_telemetry('atsVacP3', atsVacP3)
    _read_telemetry('atsVgenP1', atsVgenP1)
    _read_telemetry('atsVgenP2', atsVgenP2)
    _read_telemetry('atsVgenP3', atsVgenP3)
    _read_telemetry('atsVloadP1', atsVloadP1)
    _read_telemetry('atsVloadP2', atsVloadP2)
    _read_telemetry('atsVloadP3', atsVloadP3)
    _read_telemetry('atsIloadP1', atsIloadP1)
    _read_telemetry('atsIloadP2', atsIloadP2)
    _read_telemetry('atsIloadP3', atsIloadP3)
    _read_telemetry('atsPac1', atsPac1)
    _read_telemetry('atsPac2', atsPac2)
    _read_telemetry('atsPac3', atsPac3)
    _read_telemetry('atsVgenThresholdState', atsVgenThresholdState)
    _read_telemetry('atsVacThresholdState', atsVacThresholdState)
    _read_telemetry('atsContactorElecState', atsContactorElecState)
    _read_telemetry('atsContactorGenState', atsContactorGenState)
    _read_telemetry('atsAcState', atsAcState)
    _read_telemetry('atsGenState', atsGenState)
    _read_telemetry('atsState', atsState)


    #client attributes
    _read_attribute('atsVacP1State', atsVacP1State)
    _read_attribute('atsVacP2State', atsVacP2State)
    _read_attribute('atsVacP3State', atsVacP3State)
    _read_attribute('atsVgenP1State', atsVgenP1State)
    _read_attribute('atsVgenP2State', atsVgenP2State)
    _read_attribute('atsVgenP3State', atsVgenP3State)
    _read_attribute('atsErrorState', atsErrorState)
    _read_attribute('atsMode', atsMode)
    _read_attribute('atsConnect', atsConnect)
