from utility import bytes_to_int
from .utils import _read_attribute, _read_telemetry
from config import BYTE_ORDER


# fixed ATS to 90 byte
def extract(byte_data):
    '''
    Extract the data from an ATS message sent from the IO
    '''
    comm_state = bytes_to_int(byte_data[0])
    mode = bytes_to_int(byte_data[1])
    dev_type = bytes_to_int(byte_data[2])
    contactor_state = bytes_to_int(byte_data[3])

    vac_p1 = bytes_to_int(byte_data[4:6], byteorder=BYTE_ORDER)
    vac_p2 = bytes_to_int(byte_data[6:8], byteorder=BYTE_ORDER)
    vac_p3 = bytes_to_int(byte_data[8:10], byteorder=BYTE_ORDER)
    vac_freq = bytes_to_int(byte_data[10:12], byteorder=BYTE_ORDER)
    vgen_p1 = bytes_to_int(byte_data[12:14], byteorder=BYTE_ORDER)
    vgen_p2 = bytes_to_int(byte_data[14:16], byteorder=BYTE_ORDER)
    vgen_p3 = bytes_to_int(byte_data[16:18], byteorder=BYTE_ORDER)
    vgen_freq = bytes_to_int(byte_data[18:20], byteorder=BYTE_ORDER)
    vload_p1 = bytes_to_int(byte_data[20:22], byteorder=BYTE_ORDER)
    vload_p2 = bytes_to_int(byte_data[22:24], byteorder=BYTE_ORDER)
    vload_p3 = bytes_to_int(byte_data[24:26], byteorder=BYTE_ORDER)
    vload_freq = bytes_to_int(byte_data[26:28], byteorder=BYTE_ORDER)
    iload_p1 = bytes_to_int(byte_data[28:30], byteorder=BYTE_ORDER)
    iload_p2 = bytes_to_int(byte_data[30:32], byteorder=BYTE_ORDER)
    iload_p3 = bytes_to_int(byte_data[32:34], byteorder=BYTE_ORDER)

    gsc_type = bytes_to_int(byte_data[34])
    oil = bytes_to_int(byte_data[35:37], byteorder=BYTE_ORDER)
    coolant_temp = bytes_to_int(byte_data[37:39], byteorder=BYTE_ORDER)
    fuel = bytes_to_int(byte_data[39:41], byteorder=BYTE_ORDER)
    vbat = bytes_to_int(byte_data[41:43], byteorder=BYTE_ORDER)
    speed = bytes_to_int(byte_data[43:45], byteorder=BYTE_ORDER)
    power_total = bytes_to_int(byte_data[45:49], byteorder=BYTE_ORDER)
    power_1 = bytes_to_int(byte_data[49:53], byteorder=BYTE_ORDER)
    power_2 = bytes_to_int(byte_data[53:57], byteorder=BYTE_ORDER)
    power_3 = bytes_to_int(byte_data[57:61], byteorder=BYTE_ORDER)
    kva_total = bytes_to_int(byte_data[61:65], byteorder=BYTE_ORDER)
    kva_1 = bytes_to_int(byte_data[65:69], byteorder=BYTE_ORDER)
    kva_2 = bytes_to_int(byte_data[69:73], byteorder=BYTE_ORDER)
    kva_3 = bytes_to_int(byte_data[73:77], byteorder=BYTE_ORDER)
    pwr_counter = bytes_to_int(byte_data[77:81], byteorder=BYTE_ORDER)
    run_hours_counter = bytes_to_int(byte_data[81:85], byteorder=BYTE_ORDER)
    crank_counter = bytes_to_int(byte_data[85:89], byteorder=BYTE_ORDER)
    gsc_alarm = bytes_to_int(byte_data[89], byteorder=BYTE_ORDER)

    online_status = bytes_to_int(byte_data[90])

    _read_attribute('atsCommState', comm_state)
    _read_attribute('atsMode', mode)
    _read_attribute('atsType', dev_type)
    _read_attribute('atsContactorState', contactor_state)

    _read_telemetry('atsVacP1', vac_p1)
    _read_telemetry('atsVacP2', vac_p2)
    _read_telemetry('atsVacP3', vac_p3)
    _read_telemetry('atsVacFreq', vac_freq)
    _read_telemetry('atsVgenP1', vgen_p1)
    _read_telemetry('atsVgenP2', vgen_p2)
    _read_telemetry('atsVgenP3', vgen_p3)
    _read_telemetry('atsVgenFreq', vgen_freq)
    _read_telemetry('atsVloadP1', vload_p1)
    _read_telemetry('atsVloadP2', vload_p2)
    _read_telemetry('atsVloadP3', vload_p3)
    _read_telemetry('atsVloadFreq', vload_freq)
    _read_telemetry('atsIloadP1', iload_p1)
    _read_telemetry('atsIloadP2', iload_p2)
    _read_telemetry('atsIloadP3', iload_p3)

    _read_attribute('atsGscType', gsc_type)
    _read_telemetry('atsGscOil', oil)
    _read_telemetry('atsGscCoolantTemp', coolant_temp)
    _read_telemetry('atsGscFuel', fuel)
    _read_telemetry('atsGscVbat', vbat)
    _read_telemetry('atsGscSpeed', speed)
    _read_telemetry('atsGscPowerTotal', power_total)
    _read_telemetry('atsGscPower1', power_1)
    _read_telemetry('atsGscPower2', power_2)
    _read_telemetry('atsGscPower3', power_3)
    _read_telemetry('atsGscKvaTotal', kva_total)
    _read_telemetry('atsGscKva1', kva_1)
    _read_telemetry('atsGscKva2', kva_2)
    _read_telemetry('atsGscKva_3', kva_3)
    _read_attribute('atsGscPwrCounter', pwr_counter)
    _read_telemetry('atsGscRunHoursCounter', run_hours_counter)
    _read_telemetry('atsGscCrankCounter', crank_counter)
    _read_attribute('atsGscAlarm', gsc_alarm)

    _read_attribute('atsOnlineStatus', online_status)
