GREEN = 1
RED = 0

LED_SERVER = 0
LED_ATS = 1
LED_DC = 2
LED_ACM = 3
LED_ATU = 4
LED_1 = 5
LED_2 = 6
LED_NONE = 7
LED_ALARM = 8
LED_3G = 9
LED_ETHERNET = 10
LED_CRMU = 11
LED_4 = 12

LED_LENGTH = 15

LIST_LED = [LED_SERVER, LED_ATS, LED_DC, LED_ACM, LED_ATU, LED_1, LED_2, LED_NONE, LED_ALARM, LED_3G, LED_ETHERNET, LED_CRMU, LED_4]