PREFIX = 'https://'
DOMAIN = 'backsend-smartsite.mobifone.vn/'
API_CHECK_CONNECTION = 'api/services/app/DMTram/GetTrangThaiTuKetNoi'
API_UPDATE_SHARED_ATTRIBUTES = 'api/services/app/DMTram/ChangeValueTemplate'
API_GET_STAFF = 'api/services/app/DMNhanVienRaVaoTram/GetNhanVienRaVaoTram'
API_SAVE_LOG_RFID = 'api/services/app/DMTram/LogQuetThe'
